### ISSUE TITLE
Idris 1.3.0 build using Nix 2.0

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#20]
- [ ] Fix compilation errors caused by the upgrade from 1.2.0 to 1.3.0
- [x] Idris 1.3.0 builder for Nix 2.x
  - [x] Is this available from somewhere?
  - [ ] If not, discuss feasibility, effort and value of doing this ourselves
- [ ] We probably want to do this in a dedicated build file independent of `default.nix`
- [ ] `tparsec` dependency?

**Comment by TealG** [comment]
The `nixos-unstable` and `nixpkgs-unstable` nix channels already have `idris-1.3.0`

**Comment by clayrat** [comment]
There's https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/idris-modules/tparsec.nix

**Comment by TealG** [comment]
Tried to get the build working with `idris-1.3.0` and `tparsec` from the `nixpkgs-unstable` channel, so far without luck, it fails when building dependencies that I reported at https://github.com/NixOS/nixpkgs/issues/43493

**Comment by TealG** [comment]
This will be fixed with https://github.com/NixOS/nixpkgs/pull/43444 once it's merged.

**Comment by TealG** [comment]
Just tried, it builds fine with nixpkgs from the above PR, once it's merged I'll commit this pinned to the appropriate nixpkgs revision.

**Comment by TealG** [comment]
the PR got merged, going to commit the package definiiton pinned to that revision

**Comment by epost** [comment]
@tg-x Cool! Could you link the commit here too?
